{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fx-masterdata.serviceAccountName" . }}
  labels: {{- include "fx-masterdata.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # Set eks.amazonaws.com/role-arn here for IRSA (IAM Roles for Service Accounts).
    # That role's trust policy must include the OIDC provider for this EKS cluster.
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
