name: fx-trade-analytics-aws-opensearch

version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: fx-postgres
    environment:
      POSTGRES_DB: fxdb
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    external: true
    name: fx-trade-analytics-aws-opensearch-network