apiVersion: v1
kind: Service
metadata:
  name: {{ include "fx-opensearch-indexer.fullname" . }}
  labels: {{- include "fx-opensearch-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "fx-opensearch-indexer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
