#!/usr/bin/env bash
#
# Generates ./application-local-secrets.yml at the repo root from environment
# variables. All Spring services that depend on the file pick it up
# automatically because their application.yml has:
#
#   spring.config.import: optional:file:./application-local-secrets.yml
#
# Usage:
#   # Option A — project-namespaced env vars (preferred, no collision risk):
#   export FX_DEPLOYER_AWS_ACCESS_KEY_ID=<deployer access key id>
#   export FX_DEPLOYER_AWS_SECRET_ACCESS_KEY=<deployer secret access key>
#   npm run local:app:generate-app-secrets-yaml
#
#   # Option B — standard AWS env vars (fallback, used if Option A is unset):
#   export AWS_ACCESS_KEY_ID=<deployer access key id>
#   export AWS_SECRET_ACCESS_KEY=<deployer secret access key>
#   npm run local:app:generate-app-secrets-yaml
#
# These are the DEPLOYER user's keys (the ones printed by `npm run
# setup:aws:iam-all`). NOT the admin/bootstrap keys.

set -euo pipefail

# ── --help mode ──
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  cat <<'HELP'
═══════════════════════════════════════════════════════════════════════
 npm run local:app:generate-app-secrets-yaml — help
═══════════════════════════════════════════════════════════════════════

WHAT IT DOES
  Generates ./application-local-secrets.yml at the repo root from
  environment variables. All Spring services that depend on this file
  pick it up automatically because their application.yml has:

    spring.config.import: optional:file:./application-local-secrets.yml

  The file is gitignored — it never goes into source control.

WHAT YOU NEED TO SET BEFORE RUNNING
  Two AWS access keys for the DEPLOYER user (the user created by
  'npm run setup:aws:iam-all'). Two ways to provide them:

  Option A — project-namespaced env vars (preferred, no collision risk
  with whatever AWS profile your shell already has):

    export FX_DEPLOYER_AWS_ACCESS_KEY_ID=<deployer access key id>
    export FX_DEPLOYER_AWS_SECRET_ACCESS_KEY=<deployer secret access key>

  Option B — standard AWS env vars (fallback; used if Option A is
  unset). You may already have these set if you've configured AWS CLI:

    export AWS_ACCESS_KEY_ID=<deployer access key id>
    export AWS_SECRET_ACCESS_KEY=<deployer secret access key>

WHAT TO DO IF YOU DON'T HAVE THE DEPLOYER KEYS YET
  1. Bootstrap the IAM deployer first:
       export FX_TRADE_ANALYTICS_AWS_ACCESS_KEY=<your admin AWS key id>
       export FX_TRADE_ANALYTICS_AWS_SECRET=<your admin AWS secret>
       npm run setup:aws:iam-all
     The script prints two NEW access keys (these are the DEPLOYER
     keys).
  2. Take those new keys and use them as input to THIS command:
       export FX_DEPLOYER_AWS_ACCESS_KEY_ID=<the printed access key id>
       export FX_DEPLOYER_AWS_SECRET_ACCESS_KEY=<the printed secret>
       npm run local:app:generate-app-secrets-yaml

WHAT IT WRITES
  ./application-local-secrets.yml  (mode 600)

  Schema (see ./application-local-secrets-template.yml for full doc):

    fx:
      aws:
        access-key: ...
        secret-key: ...

WHICH SERVICES READ THIS FILE
  - fx-masterdata-service     (OpenSearch deployment sync feature)
  - fx-trade-service          (search-path SigV4 signing via fx-search-client)
  - fx-opensearch-indexer     (write-path SigV4 signing via fx-search-client)

  Each of those services' application.yml does an
  'spring.config.import: optional:file:./application-local-secrets.yml',
  loaded on startup.

AFTER GENERATING
  Restart any running Spring services so they pick up the credentials:
    npm run local:app:run-all

═══════════════════════════════════════════════════════════════════════
HELP
  exit 0
fi

# Project-namespaced wins; standard AWS env names are the fallback.
ACCESS_KEY="${FX_DEPLOYER_AWS_ACCESS_KEY_ID:-${AWS_ACCESS_KEY_ID:-}}"
SECRET_KEY="${FX_DEPLOYER_AWS_SECRET_ACCESS_KEY:-${AWS_SECRET_ACCESS_KEY:-}}"

if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ]; then
  echo "ERROR: AWS deployer credentials not found in env." >&2
  echo "" >&2
  echo "  Set EITHER:" >&2
  echo "    export FX_DEPLOYER_AWS_ACCESS_KEY_ID=<key id>" >&2
  echo "    export FX_DEPLOYER_AWS_SECRET_ACCESS_KEY=<secret>" >&2
  echo "  OR (standard AWS env names):" >&2
  echo "    export AWS_ACCESS_KEY_ID=<key id>" >&2
  echo "    export AWS_SECRET_ACCESS_KEY=<secret>" >&2
  echo "" >&2
  echo "  These are the DEPLOYER user's keys (printed by 'npm run setup:aws:iam-all')," >&2
  echo "  NOT the admin / bootstrap keys." >&2
  exit 1
fi

OUTPUT="./application-local-secrets.yml"
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [ -f "$OUTPUT" ]; then
  echo "→ $OUTPUT exists; overwriting."
fi

cat > "$OUTPUT" <<EOF
# Auto-generated by 'npm run local:app:generate-app-secrets-yaml' at ${GENERATED_AT}.
# Re-run the command to refresh; this file is gitignored — never check it in.
# Template + structure documentation: ./application-local-secrets-template.yml
#
# Loaded by every Spring service that imports it via:
#   spring.config.import: optional:file:./application-local-secrets.yml

fx:
  aws:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
EOF

# Restrict perms — secrets file shouldn't be world-readable
chmod 600 "$OUTPUT" 2>/dev/null || true

LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
echo "✓ Wrote ${OUTPUT} (${LINES} lines, mode 600)"
echo ""
echo "Restart any running Spring services to pick up the credentials:"
echo "  npm run local:app:run-all"
